sudo: required
language: generic
services: docker
script:
- docker pull rekka/tectonic
- docker run --mount src=$TRAVIS_BUILD_DIR/deeplearning_notes,target=/usr/src/tex,type=bind
  rekka/tectonic tectonic main.tex
deploy:
  provider: releases
  api_key:
    secure: YQc6teB7A3XMjzBmp2tZC2lVkXxO2zuHQ9FTQLYMZZzTr2h7/+djkfy2MINECpcC9dAIGNF1r+JhWCPUQGyWvuZ75Eq1YROwrTnje0nx43yW7Ftqn7KiYcMkM8u1bQLgTITVFxnrG63flXjpCfhtQ1UFzhp+tUqWtXqYjLBH7obvNeXJdM69fjBUmSoEJEhlvAo6o26X908HaLiLJ4r0ihkJyMtKpL43AmIp4zPrbk02WuozgQKYsGEg5yd3tNPSpd8yxDCe9qO+LC31rc5KYqAMR3n25nNTfkcc3wvzrNV4yMQg1dyDzAxSBnamXaI69BVjHqhpi2DE62bI5TISVr8kF59cLXoi/qWzb1h3pHWihHicLfqbRTAbY4RvEcFrXk6scFQ4xJcnm7HYmnpTyuSz8hNEzx2vqbYG7yu+pibSrRUSxVYTNdzsVfG/DtLmqz+ldFB+H8zrmGalWdq5jJU+7da2C7WSNRH9NWSl5Mb10CbhIUpIkV+P4TudjTI++02hQUqhzuzvyBZJWYBU3VWUwCKpnlq81IxlSKBwc66slQGOjj1/T5P6M04zuEz3w39uHt0KiZztf6EDULD8+1YkMjcslMkz6TvAgnZtV6EIY8KCRbfBrnw5/yM40HjuU5iVt0bPT9g33U0hqe+u278NvC+HI9qagq3REERuq1M=
  file: "./deeplearning_notes/main.pdf"
  skip_cleanup: true
  on:
    tags: true
    branch: master
